### ISSUE TITLE
Broken Lint

### ISSUE THREAD

**Issue by ChrisMacNaughton** [stub42/layer-apt#1]
It looks like this commit : https://git.launchpad.net/layer-apt/commit/?id=5923fd84ce7cf2628e3f372ddc8f3ddb22ab8982 breaks lint, specifically:
https://git.launchpad.net/layer-apt/tree/lib/charms/apt.py#n132 breaks with `lib/charms/apt.py:132:25: E261 at least two spaces before inline comment`

**Comment by stub42** [comment]
Looks like I fixed this.
