### ISSUE TITLE
'error' is not a valid workload state

### ISSUE THREAD

**Issue by afreiberger** [stub42/layer-apt#3]
Filed bug on postgresql-charm that appears to be a potential bug in apt layer.
lib/charm/apt.py line 127 using status_set(None) causes infinite hook error when unit is in error state under juju 2.4.1.

May want to either change status_set to mask 'error' as 'blocked', or consider that the layer-apt install_queued could/should set state to 'maintenance' during the process of installing packages.

https://bugs.launchpad.net/postgresql-charm/+bug/1784482

**Comment by stub42** [comment]
Tracking in the Launchpad bug
